### ISSUE TITLE
Circular References

### ISSUE THREAD

**Issue by Jefersonblc** [XMundek/FastAutoMapper#1]
Hi,

I'm trying to map my EF models to some DTO models, but when I try to map any model with circular reference I get an infinite loop.

I couldn't find a way to treat this problem

**Comment by XMundek** [comment]
This is a known problem. Currently, this library does not support circular references. In the future it will be solved, but it is not easy, without any loss of performance. If you have few type definitions with circular references, you can attach the own functions to this automapper that should be fix this problem.
Example:
Mapper.AddMapping<SourceAddress, DestinationAddress>(
a=>new DestinationAddress(){Street = a.AddressLine1});

**Comment by XMundek** [comment]
I tested solution with tracking circular references - but it degrades performance of mapping 2-3 times, so i decided to not implement automatic solution.
