### ISSUE TITLE
Not compatible with dotnet core 2.2

### ISSUE THREAD

**Issue by frankhaugen** [XMundek/FastAutoMapper#2]
There shouldn't be any reason for this not to support dotnet, so please look into making it compatible

thank you for you hard work!

**Comment by XMundek** [comment]
I needed this library for a project in the .NET Framework. Unfortunately, it is not possible to convert it to .NET Standard easily. It is necessary do separate versions of the library for the .NET Core and .NET Framework based on the same shared code (I use libraries that are available in the .NET Core and .NET Framework, but not .NET Standard) - in which you need to make a few changes. Most likely, the version on .NET Core will be available in a month.

**Comment by XMundek** [comment]
Done
